name: AllAdvancementsChallenge
version: 0.2.5
main: de.idk_jay.Main
api-version: '1.21'
author: idk_jay
commands:
  advancements:
    description: Displays the list of all earned advancements.
    usage: /advancements
  agui:
    description: Opens the Advancements GUI.
    usage: /agui
  achallenge:
    description: Manages the challenge.
    usage: /achallenge <start|pause|resume|stop|reset|lang|autosave|reload>
permissions:
  challenge.admin.start:
    description: Allows starting the challenge.
    default: op
  challenge.admin.pause:
    description: Allows pausing and resuming the challenge.
    default: op
  challenge.admin.stop:
    description: Allows stopping the challenge.
    default: op
  challenge.admin.reset:
    description: Allows resetting the challenge.
    default: op
  challenge.admin.lang:
    description: Allows changing the language.
    default: op
  challenge.admin.autosave:
    description: Allows changing the autosave interval.
    default: op
  challenge.admin.reload:
    description: Allows reloading the plugin.
    default: op
  challenge.admin.bypasspause:
    description: Allows movement and interaction during pause mode.
    default: op